sudo: required

services:
  - docker

before_install:
  - docker build -t tejakantamneni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tejakantamneni/docker-react npm run test

language: generic 