sudo: required

services:
  - docker

before_install:
  - docker build -t tejakantamneni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tejakantamneni/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "tk-docker"
  env: "TkDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-547472556924"
  bucket_path: "tk-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY